server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jpl_app?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
  redis:
    port:6379
    host:localhost

logging:
  level:
    com.example: debug